baseURL = 'https://futur.renocrypt.com'
languageCode = 'en-us'
title = 'FuturCipher by renocrypt'
theme = 'blist'
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false

[languages]

[languages.en]
contentDir = "content/en" #English
weight = 1
languageName = "English"

[languages.en.params]
introTitle = "FuturCipher: Insight Into What's Next by RenoCrypt"
introSubtitle = "Translating Complex Patterns into Understandable Narratives. Deciphering the Delicate Dance of Business and Finance"
introPhoto = "/picture.jpg"
logo = "/futur-logo.png"

[[languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 1

[[languages.en.menu.main]]
name = "Biology"
url = "biology"
weight = 2

[[languages.en.menu.main]]
name = "Psychology"
url = "psychology"
weight = 3

[params]
ascentColor = 'bg-blue-200 dark:bg-green-900'
# Enable the darkmode toggle in header
darkModeToggle = true
# Enable search in header
enableSearch = true
searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author",
]
# Custom copyright - optional
copyright = "Copyright Â© 2024 - Benji Peng Honeycutt. Â· FuturCipher Â· RenoCrypt Â· All rights reserved"
favicon = "/favicon.svg"

[params.homepage.social]
title = "Find me in"
description = "Seeking thrills or en route to excitement? Find me on the dance floor ðŸ’š"

[[params.homepage.social.icons]]
website = "linkedin"
url = "https://linkedin.com/in/benjiph"

[[params.homepage.social.icons]]
website = "github"
url = "https://github.com/benjipeng"

[[params.homepage.social.icons]]
website = "twitter"
url = "https://twitter.com/benjipeng"

[[params.homepage.social.icons]]
website = "instagram"
url = "https://www.instagram.com/ben_flyer/"

[[params.homepage.social.icons]]
website = "googlescholar"
url = "https://benji.renocrypt.com/"


[[menu.main]]
name = "About"
url = "https://www.appcubic.com"

# syntax highlight settings
[markup]

[markup.highlight]
style = "dracula"

[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true
googleAnalytics = 'G-PGM8E71KE2'

[outputs]
home = ["HTML", "RSS", "JSON"]
